const siteContent = {
    "en": {
        "pageTitle": "Mohamad Bashar - Portfolio",
        "logoText": "MB.",
        "navHome": "Home",
        "navAbout": "About",
        "navSkills": "Skills",
        "navWork": "Work",
        "navExperience": "Experience",
        "navContact": "Contact",
        "heroName": "<span class=\"highlight-name\">Mohamad Bashar</span> - Student & Aspiring Developer", // Name highlighted
        "heroHeadline": "Passionate high school student diving deep into the world of programming, especially <span class=\"highlight-keyword\">Python</span> and <span class=\"highlight-keyword\">TensorFlow</span>. Driven by a love for learning and academic challenges in <span class=\"highlight-keyword\">Math</span>, <span class=\"highlight-keyword\">Physics</span>, and <span class=\"highlight-keyword\">Chemistry</span>. Eager to build, contribute, and grow within the tech community.",
        "heroAcademicPassion": "My academic curiosity fuels my technical drive, creating a unique blend of <span class=\"highlight-text\">analytical thinking</span> and <span class=\"highlight-text\">creative problem-solving</span>.",
        "aboutTitle": "About Me",
        "aboutPara1": "Hi there! I\"m Mohamad, a 17-year-old high school student with a <span class=\"highlight-text\">strong foundation in Math, Physics, and Chemistry</span>, and an even stronger passion for coding. My journey into technology started with <span class=\"highlight-keyword\">Python</span>, and I quickly fell in love with its power and versatility.",
        "aboutPara2": "Currently, I\"m focusing on deepening my expertise in <span class=\"highlight-keyword\">TensorFlow</span> and exploring the vast possibilities of <span class=\"highlight-text\">machine learning</span>. I\"m always eager to tackle new challenges, learn new technologies, and collaborate on exciting projects. I believe in <span class=\"highlight-text\">hard work</span> and <span class=\"highlight-text\">continuous learning</span> to become a top-notch developer and make meaningful contributions.",
        "skillsTitle": "My Skills",
        "skillsLangTitle": "Programming Languages",
        "skillsLangPy": "Python (Expert)",
        "skillsLangJs": "JavaScript (Novice)",
        "skillsLangHtml": "HTML5 (Novice)",
        "skillsLangCss": "CSS3 (Novice)",
        "skillsFrameworkTitle": "Frameworks & Libraries",
        "skillsFrameworkTf": "TensorFlow (Intermediate)",
        "skillsToolsTitle": "Tools & Platforms",
        "skillsToolsGit": "Git & GitHub",
        "skillsToolsVs": "VS Code",
        "skillsAcademicTitle": "Academic Strengths",
        "skillsAcademicMath": "Mathematics",
        "skillsAcademicPhys": "Physics",
        "skillsAcademicChem": "Chemistry",
        "workTitle": "My Work",
        "workDemoTitle": "Demo Project",
        "workDemoDesc": "A sample project showcasing basic implementation. Replace this with details about your actual work.",
        "workDemoSkills": "Skills: HTML, CSS, JS",
        "workDemoLink": "View Project",
        "workVectorTitle": "Vector Visualizer",
        "workVectorDesc": "An interactive app built with Python and Streamlit to help students visualize physics vectors. Graph vectors with different colors and sizes. A contribution to my school, created in Grade 9 (2022).",
        "workVectorSkills": "Skills: Python, Streamlit",
        "workVectorLiveLink": "View Live App",
        "workVectorGithubLink": "View on GitHub",
        "workVerbsTitle": "Irregular Verbs Quiz",
        "workVerbsDesc": "An interactive and fun quiz app built with Python and Streamlit to help users practice English irregular verbs. Includes scoring and feedback.",
        "workVerbsSkills": "Skills: Python, Streamlit",
        "workVerbsLiveLink": "Try the Quiz",
        "workVerbsGithubLink": "View on GitHub",
        "experienceTitle": "Experience & Certifications",
        "expIeltsTitle": "<span class=\"highlight-cert\">IELTS Academic</span>",
        "expIeltsDesc": "Achieved an overall band score of 7.0 (CEFR Level C1), demonstrating proficient English language skills for academic and professional environments. (April 2025)",
        "expTfTitle": "<span class=\"highlight-cert\">Udemy: TensorFlow for Deep Learning Bootcamp</span>",
        "expTfDesc": "Completed a comprehensive 63-hour bootcamp covering TensorFlow fundamentals and applications in deep learning. (May 2025)",
        "expPyTitle": "<span class=\"highlight-cert\">Udemy: Python Mega Course: Learn Python in 60 Days, Build 20 Apps</span>",
        "expPyDesc": "Finished a 52-hour intensive course focused on Python programming, including building multiple real-world applications. (July 2023)",
        "expRitTitle": "RIT Dubai: 14th Annual Engineering Competition",
        "expRitDesc": "Participated in the Software Engineering track of the competition, gaining valuable experience in competitive programming and teamwork. (November 2024)",
        "expRadioTitle": "School Award: 1st Place - Radio Program Contribution",
        "expRadioDesc": "Recognized for outstanding technical and creative contributions to the school\"s radio program during the first semester.",
        "expAcademicTitle": "School Award: Academic Excellence (3rd Center)",
        "expAcademicDesc": "Achieved 3rd position in academic ranking for the 11th grade (Branch 4) during the first semester of the 2023-2024 academic year.",
        "expUcmasTitle": "<span class=\"highlight-cert\">UCMAS National Competition - 2nd Runner Up</span>",
        "expUcmasDesc": "Achieved Second Runner Up in the 14th National Abacus & Mental Arithmetic and Listening Skill Competition (Elementary B / C3 Category) held in Dubai, UAE. (May 2017)",
        "gratitudeTitle": "Gratitude",
        "gratitudeText": "I wouldn\"t be where I am today without the unwavering support and sacrifices of my family, especially my parents who fueled my passion and always believed in me. A special thanks also goes to my two brothers, my friends, and my teachers for their constant encouragement and guidance. Thank you all!",
        "contactTitle": "Get In Touch",
        "contactSubtext": "Interested in collaborating or have any questions? Feel free to reach out!",
        "contactEmailLink": "Your Email Address",
        "contactGithubLink": "GitHub Profile",
        "footerText": "© 2025 Mohamad Bashar. All rights reserved."
    },
    "ar": {
        "pageTitle": "محمد بشار - ملف شخصي",
        "logoText": "م.ب.",
        "navHome": "الرئيسية",
        "navAbout": "عني",
        "navSkills": "مهاراتي",
        "navWork": "أعمالي",
        "navExperience": "الخبرات",
        "navContact": "تواصل معي",
        "heroName": "<span class=\"highlight-name\">محمد بشار</span> - طالب ومطور طموح", // Name highlighted
        "heroHeadline": "طالب ثانوي شغوف يغوص في أعماق عالم البرمجة، وخاصة <span class=\"highlight-keyword\">بايثون</span> و <span class=\"highlight-keyword\">TensorFlow</span>. يقودني حبي للتعلم وشغفي بالتحديات الأكاديمية في <span class=\"highlight-keyword\">الرياضيات</span> و <span class=\"highlight-keyword\">الفيزياء</span> و <span class=\"highlight-keyword\">الكيمياء</span>. أتطلع بحماس للبناء والمساهمة والنمو ضمن مجتمع التكنولوجيا المتطور.",
        "heroAcademicPassion": "فضولي الأكاديمي يغذي دافعي التقني، مما يخلق مزيجًا فريدًا من <span class=\"highlight-text\">التفكير التحليلي</span> و <span class=\"highlight-text\">حل المشكلات الإبداعي</span>.",
        "aboutTitle": "نبذة عني",
        "aboutPara1": "أهلاً بك! أنا محمد، طالب ثانوي في السابعة عشرة، أمتلك <span class=\"highlight-text\">أساساً متيناً في الرياضيات والفيزياء والكيمياء</span>، وشغفاً لا حدود له بالبرمجة. بدأت رحلتي الشيقة في عالم التكنولوجيا مع <span class=\"highlight-keyword\">بايثون</span>، وسرعان ما أسرتني قوتها ومرونتها المذهلة.",
        "aboutPara2": "أركز حالياً على صقل خبرتي في <span class=\"highlight-keyword\">TensorFlow</span> واستكشاف الإمكانيات اللامحدودة لـ<span class=\"highlight-text\">تعلم الآلة</span>. أنا دائماً متعطش لمواجهة تحديات جديدة، وتعلم تقنيات مبتكرة، والمشاركة في مشاريع ملهمة. أؤمن بأن <span class=\"highlight-text\">العمل الجاد</span> و <span class=\"highlight-text\">التعلم المستمر</span> هما مفتاح التميز وتحقيق مساهمات مؤثرة.",
        "skillsTitle": "مهاراتي",
        "skillsLangTitle": "لغات البرمجة",
        "skillsLangPy": "بايثون (خبير)",
        "skillsLangJs": "جافاسكريبت (مبتدئ)",
        "skillsLangHtml": "HTML5 (مبتدئ)",
        "skillsLangCss": "CSS3 (مبتدئ)",
        "skillsFrameworkTitle": "أطر العمل والمكتبات",
        "skillsFrameworkTf": "TensorFlow (متوسط)",
        "skillsToolsTitle": "الأدوات والمنصات",
        "skillsToolsGit": "Git و GitHub",
        "skillsToolsVs": "VS Code",
        "skillsAcademicTitle": "نقاط القوة الأكاديمية",
        "skillsAcademicMath": "الرياضيات",
        "skillsAcademicPhys": "الفيزياء",
        "skillsAcademicChem": "الكيمياء",
        "workTitle": "أعمالي",
        "workDemoTitle": "مشروع تجريبي",
        "workDemoDesc": "مشروع نموذجي يعرض التنفيذ الأساسي. استبدل هذا بتفاصيل حول عملك الفعلي.",
        "workDemoSkills": "المهارات: HTML, CSS, JS",
        "workDemoLink": "عرض المشروع",
        "workVectorTitle": "مصور المتجهات",
        "workVectorDesc": "تطبيق تفاعلي تم إنشاؤه باستخدام Python و Streamlit لمساعدة الطلاب على تصور متجهات الفيزياء. رسم المتجهات بألوان وأحجام مختلفة. مساهمة لمدرستي، تم إنشاؤها في الصف التاسع (2022).",
        "workVectorSkills": "المهارات: Python, Streamlit",
        "workVectorLiveLink": "عرض التطبيق المباشر",
        "workVectorGithubLink": "عرض على GitHub",
        "workVerbsTitle": "اختبار الأفعال الشاذة",
        "workVerbsDesc": "تطبيق اختبار تفاعلي وممتع تم إنشاؤه باستخدام Python و Streamlit لمساعدة المستخدمين على ممارسة الأفعال الشاذة في اللغة الإنجليزية. يتضمن تسجيل النقاط وتقديم الملاحظات.",
        "workVerbsSkills": "المهارات: Python, Streamlit",
        "workVerbsLiveLink": "جرب الاختبار",
        "workVerbsGithubLink": "عرض على GitHub",
        "experienceTitle": "الخبرات والشهادات",
        "expIeltsTitle": "<span class=\"highlight-cert\">IELTS الأكاديمي</span>",
        "expIeltsDesc": "حصلت على درجة 7.0 (مستوى C1 حسب CEFR)، مما يدل على إتقان اللغة الإنجليزية للبيئات الأكاديمية والمهنية. (أبريل 2025)",
        "expTfTitle": "<span class=\"highlight-cert\">Udemy: معسكر TensorFlow للتعلم العميق</span>",
        "expTfDesc": "أكملت معسكرًا تدريبيًا شاملاً لمدة 63 ساعة يغطي أساسيات TensorFlow وتطبيقاته في التعلم العميق. (مايو 2025)",
        "expPyTitle": "<span class=\"highlight-cert\">Udemy: دورة بايثون الضخمة: تعلم بايثون في 60 يومًا، ابنِ 20 تطبيقًا</span>",
        "expPyDesc": "أنهيت دورة مكثفة لمدة 52 ساعة تركز على برمجة بايثون، بما في ذلك بناء تطبيقات متعددة للعالم الحقيقي. (يوليو 2023)",
        "expRitTitle": "RIT دبي: مسابقة الهندسة السنوية الرابعة عشرة",
        "expRitDesc": "شاركت بفعالية في مسار هندسة البرمجيات بالمسابقة، مما أتاح لي فرصة ثمينة لصقل مهاراتي في البرمجة التنافسية وتجربة العمل الجماعي المثمر. (نوفمبر 2024)",
        "expRadioTitle": "جائزة مدرسية: المركز الأول - مساهمة في برنامج الإذاعة",
        "expRadioDesc": "تم تكريمي لتقديم مساهمات فنية وإبداعية بارزة دعمت برنامج الإذاعة المدرسية خلال الفصل الدراسي الأول.",
        "expAcademicTitle": "جائزة مدرسية: التفوق الأكاديمي (المركز الثالث)",
        "expAcademicDesc": "حصلت على المركز الثالث في الترتيب الأكاديمي للصف الحادي عشر (فرع 4) خلال الفصل الدراسي الأول للعام الدراسي 2023-2024.",
        "expUcmasTitle": "<span class=\"highlight-cert\">مسابقة UCMAS الوطنية - المركز الثالث</span>",
        "expUcmasDesc": "حصلت على المركز الثالث (Second Runner Up) في المسابقة الوطنية الرابعة عشرة للحساب الذهني باستخدام العداد والاستماع (فئة Elementary B / C3) التي أقيمت في دبي، الإمارات العربية المتحدة. (مايو 2017)",
        "gratitudeTitle": "شكر وتقدير",
        "gratitudeText": "لم أكن لأصل إلى ما أنا عليه اليوم لولا الدعم والتضحيات التي لا تقدر بثمن من عائلتي، وخاصة والديّ اللذين أشعلا شغفي وآمنا بي دائمًا. شكر خاص أيضًا لأخويّ وأصدقائي ومعلميّ على تشجيعهم وتوجيههم المستمر. شكرًا لكم جميعًا!",
        "contactTitle": "تواصل معي",
        "contactSubtext": "هل أنت مهتم بالتعاون أو لديك أي أسئلة؟ لا تتردد في التواصل!",
        "contactEmailLink": "عنوان بريدك الإلكتروني",
        "contactGithubLink": "ملف GitHub الشخصي",
        "footerText": "© 2025 محمد بشار. جميع الحقوق محفوظة."
    }
};

